### ISSUE TITLE
Exception when publication returns an empty array.

### ISSUE THREAD

**Issue by ziedmahdi** [johanbrook/meteor-publication-collector#28]
When testing the published data for this collection, `userId = null`, I get `Publish function can only return a Cursor or an array of Cursors`
```js
Meteor.publish('kibanaDashboards', function () {
    //make sure that the user is logged in
    if (this.userId) {
        return KibanaDashboards.find({});
    } else {
        this.stop();
        return [];
    }
});
```
I think the collector should expect empty arrays and `null` values.

**Comment by nkahnfr** [comment]
Hi,

The error is expected as you must only return a cursor or an array of cursors (see related [Meteor documentation](http://docs.meteor.com/api/pubsub.html#Meteor-publish)).

You can fix your code by replacing the ```else```statement with the following:
```
} else {
    this.ready();
    return;
}
```
_You can even omit the ```return;``` statement._

**Comment by ziedmahdi** [comment]
so [in related docs](http://docs.meteor.com/api/pubsub.html#Meteor-publish) 
```js
// Sometimes publish a query, sometimes publish nothing.
Meteor.publish('secretData', function () {
  if (this.userId === 'superuser') {
    return SecretData.find();
  } else {
    // Declare that no data is being published. If you leave this line out,
    // Meteor will never consider the subscription ready because it thinks
    // you're using the `added/changed/removed` interface where you have to
    // explicitly call `this.ready`.
    return [];
  }
});
```

so a publication can return an empty array.
Also, stopping a publication (`this.stop()`) is not same as marking it as ready (`this.ready()`).

**Comment by nkahnfr** [comment]
@ziedmahdi OK, I checked the [source code](https://github.com/meteor/meteor/blob/master/packages/ddp-server/livedata_server.js#L1053-L1122) and an empty array should indeed be supported as a return value for a publication (BTW a ```null``` value is not correct). Basically it should only state that the publication is ready.

That said, IMHO your PR is still incorrect due to [```this.ready();``` having been moved outside the ```if``` statement dealing with publications that return cursors](https://github.com/johanbrook/meteor-publication-collector/blob/master/publication-collector.js#L123).

I will work on a PR that will fix the empty array use-case without breaking the low-level interface one.

**Comment by nkahnfr** [comment]
@ziedmahdi Let me know if that PR does not work in your case.

@johanbrook Let me know if you need more details.
